package com.wms.service;
import com.wms.common.BizException; import com.wms.entity.*; import com.wms.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*;
@Service public class EquipmentService {
 private final EquipmentRepository equipmentRepo; private final EquipmentPartRepository partRepo; private final EquipmentUsageRepository usageRepo; private final ProductRepository productRepo; private final InventoryRepository inventoryRepo;
 public EquipmentService(EquipmentRepository a,EquipmentPartRepository b,EquipmentUsageRepository c,ProductRepository d,InventoryRepository e){equipmentRepo=a;partRepo=b;usageRepo=c;productRepo=d;inventoryRepo=e;}
 public List<Map<String,Object>> list(String keyword){String k=keyword==null?"":keyword.trim(); return equipmentRepo.findByCodeContainingOrNameContaining(k,k).stream().map(this::equipmentMap).toList();}
 @Transactional public Map<String,Object> save(Long id,Map<String,Object> req){Equipment e=id==null?new Equipment():equipmentRepo.findById(id).orElseThrow(()->new BizException("设备不存在")); String code=str(req,"code"); if(code==null)throw new BizException("设备编码不能为空"); if(id==null&&equipmentRepo.existsByCode(code))throw new BizException("设备编码已存在"); e.setCode(code);e.setName(required(req,"name","设备名称不能为空"));e.setModel(str(req,"model"));e.setLocation(str(req,"location"));e.setStatus(Optional.ofNullable(str(req,"status")).orElse("RUNNING"));e.setManufacturer(str(req,"manufacturer"));e.setRemark(str(req,"remark")); return equipmentMap(equipmentRepo.save(e));}
 @Transactional public Map<String,Object> bindPart(Long equipmentId,Map<String,Object> req){Long productId=num(req,"productId"); Equipment e=equipmentRepo.findById(equipmentId).orElseThrow(()->new BizException("设备不存在")); Product p=productRepo.findById(productId).orElseThrow(()->new BizException("备件不存在")); EquipmentPart x=partRepo.findByEquipmentIdAndProductId(equipmentId,productId).orElseGet(EquipmentPart::new);x.setEquipment(e);x.setProduct(p);x.setInstalledQty(Optional.ofNullable(integer(req,"installedQty")).orElse(1));x.setLifeCycleDays(integer(req,"lifeCycleDays"));x.setConsumptionCycleDays(integer(req,"consumptionCycleDays"));x.setProcurementLeadDays(integer(req,"procurementLeadDays"));x.setSafetyStock(Optional.ofNullable(integer(req,"safetyStock")).orElse(0));return partMap(partRepo.save(x));}
 public List<Map<String,Object>> parts(Long id){return partRepo.findByEquipmentId(id).stream().map(this::partMap).toList();}
 public List<Map<String,Object>> alerts(){List<Map<String,Object>> out=new ArrayList<>(); for(EquipmentPart p:partRepo.findAll()){int stock=inventoryRepo.findAllByProductId(p.getProduct().getId()).stream().mapToInt(Inventory::getQty).sum(); int cycle=Optional.ofNullable(p.getConsumptionCycleDays()).orElse(0), lead=Optional.ofNullable(p.getProcurementLeadDays()).orElse(0); int threshold=p.getSafetyStock()+(cycle>0?Math.max(1,(int)Math.ceil((double)lead/cycle))*p.getInstalledQty():p.getSafetyStock()); boolean shortage=stock<=threshold; boolean due=p.getNextExpectedUseDate()!=null&&!p.getNextExpectedUseDate().isAfter(LocalDate.now().plusDays(Math.max(lead,7))); if(shortage||due){Map<String,Object> m=partMap(p);m.put("stockQty",stock);m.put("reorderPoint",threshold);m.put("alertType",shortage?"STOCK":"LIFECYCLE");out.add(m);}} return out;}
 @Transactional public void recordUsage(Equipment e,Product product,int qty,String orderNo){if(e==null)return; partRepo.findByEquipmentIdAndProductId(e.getId(),product.getId()).ifPresent(p->{LocalDate today=LocalDate.now(); p.setLastUsedDate(today); int days=Optional.ofNullable(p.getLifeCycleDays()).orElse(p.getConsumptionCycleDays()); if(days>0)p.setNextExpectedUseDate(today.plusDays(days)); EquipmentUsage u=new EquipmentUsage();u.setEquipment(e);u.setProduct(product);u.setQty(qty);u.setOutboundOrderNo(orderNo);u.setLifeCycleDays(p.getLifeCycleDays());u.setNextExpectedUseDate(p.getNextExpectedUseDate());usageRepo.save(u);});}
 private Map<String,Object> equipmentMap(Equipment e){Map<String,Object>m=new LinkedHashMap<>();m.put("id",e.getId());m.put("code",e.getCode());m.put("name",e.getName());m.put("model",e.getModel());m.put("location",e.getLocation());m.put("status",e.getStatus());m.put("manufacturer",e.getManufacturer());m.put("remark",e.getRemark());return m;}
 private Map<String,Object> partMap(EquipmentPart p){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.getId());m.put("equipmentId",p.getEquipment().getId());m.put("equipmentCode",p.getEquipment().getCode());m.put("equipmentName",p.getEquipment().getName());m.put("productId",p.getProduct().getId());m.put("sku",p.getProduct().getSku());m.put("productName",p.getProduct().getName());m.put("installedQty",p.getInstalledQty());m.put("lifeCycleDays",p.getLifeCycleDays());m.put("consumptionCycleDays",p.getConsumptionCycleDays());m.put("procurementLeadDays",p.getProcurementLeadDays());m.put("safetyStock",p.getSafetyStock());m.put("lastUsedDate",p.getLastUsedDate());m.put("nextExpectedUseDate",p.getNextExpectedUseDate());return m;}
 private String str(Map<String,Object>m,String k){Object v=m.get(k);return v==null?null:String.valueOf(v).trim();} private String required(Map<String,Object>m,String k,String msg){String v=str(m,k);if(v==null||v.isEmpty())throw new BizException(msg);return v;} private Long num(Map<String,Object>m,String k){Object v=m.get(k);if(v==null||String.valueOf(v).isBlank())return null;return Long.valueOf(String.valueOf(v));} private Integer integer(Map<String,Object>m,String k){Long v=num(m,k);return v==null?null:v.intValue();}
}
