-- JimuReport 2.5.1 DDL (compact)
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `chat2bi_assistant` ( `id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `avatar` varchar(20) NULL DEFAULT NULL, `description` varchar(500) NULL DEFAULT NULL, `welcome` varchar(500) NULL DEFAULT NULL, `domain_id` varchar(32) NULL DEFAULT NULL, `domain_ids` varchar(1000) NULL DEFAULT NULL, `show_sql` varchar(1) NULL DEFAULT NULL, `status` varchar(20) NULL DEFAULT NULL, `questions_json` text NULL, `sort_no` int(11) NULL DEFAULT NULL, `perm_json` text NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT 0, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_c2b_assistant_domain`(`domain_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_conversation` ( `id` varchar(32) NOT NULL, `assistant_id` varchar(32) NOT NULL, `domain_id` varchar(32) NULL DEFAULT NULL, `title` varchar(100) NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT 0, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_c2b_conv_ast_user`(`assistant_id`, `create_by`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_domain` ( `id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `description` varchar(500) NULL DEFAULT NULL, `datasource_id` varchar(36) NULL DEFAULT NULL, `status` varchar(20) NULL DEFAULT NULL, `sort_no` int(11) NULL DEFAULT NULL, `joins_json` text NULL, `perm_json` text NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT 0, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_message` ( `id` varchar(32) NOT NULL, `conversation_id` varchar(32) NOT NULL, `role` varchar(10) NULL DEFAULT NULL, `content` text NULL, `msg_json` mediumtext NULL, `sort_no` int(11) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_c2b_msg_conv`(`conversation_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_table` ( `id` varchar(32) NOT NULL, `domain_id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `label` varchar(100) NULL DEFAULT NULL, `mode` varchar(20) NULL DEFAULT NULL, `sql_text` text NULL, `columns_json` text NULL, `sort_no` int(11) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT 0, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_c2b_table_domain`(`domain_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_table_meta` ( `id` varchar(32) NOT NULL, `db_source_type` varchar(32) NOT NULL, `db_source_id` varchar(32) NOT NULL, `schema_name` varchar(128) NULL DEFAULT NULL, `table_name` varchar(128) NOT NULL, `source_comment` varchar(512) NULL DEFAULT NULL, `table_comment` varchar(512) NULL DEFAULT NULL, `columns_json` text NOT NULL, `relations_json` text NULL, `is_enabled` tinyint(4) NOT NULL DEFAULT 1, `synced_time` datetime NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uk_source_table`(`db_source_type`, `db_source_id`, `schema_name`, `table_name`) USING BTREE, INDEX `idx_source`(`db_source_type`, `db_source_id`) USING BTREE, INDEX `idx_table_name`(`table_name`) USING BTREE, INDEX `idx_table_name_comment`(`table_name`, `source_comment`(320), `table_comment`(320)) USING BTREE, INDEX `idx_table_comment`(`table_comment`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_term` ( `id` varchar(32) NOT NULL, `domain_id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `synonyms_json` text NULL, `description` varchar(500) NULL DEFAULT NULL, `apply_kind` varchar(20) NULL DEFAULT NULL, `apply_time` varchar(50) NULL DEFAULT NULL, `apply_clause` varchar(500) NULL DEFAULT NULL, `sort_no` int(11) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT 0, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_c2b_term_domain`(`domain_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `chat2bi_topic` ( `id` varchar(32) NOT NULL, `domain_id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `description` varchar(500) NULL DEFAULT NULL, `status` varchar(20) NULL DEFAULT NULL, `fields_json` text NULL, `sort_no` int(11) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT 0, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_c2b_topic_domain`(`domain_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `demo` ( `id` varchar(50) NOT NULL, `name` varchar(30) NULL DEFAULT NULL, `key_word` varchar(255) NULL DEFAULT NULL, `punch_time` datetime NULL DEFAULT NULL, `salary_money` decimal(10, 3) NULL DEFAULT NULL, `bonus_money` double(10, 2) NULL DEFAULT NULL, `sex` varchar(2) NULL DEFAULT NULL, `age` int(11) NULL DEFAULT NULL, `birthday` date NULL DEFAULT NULL, `email` varchar(50) NULL DEFAULT NULL, `content` varchar(1000) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `sys_org_code` varchar(64) NULL DEFAULT NULL, `tenant_id` int(10) NULL DEFAULT 0, `update_count` int(11) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `huiyuan_age` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_fengongsi` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, `type` varchar(32) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_huoyuedu` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_sex` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_work` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_wxtl` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_wxtlshuliang` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` int(10) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `huiyuan_xueli` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `value` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ins_claim` ( `id` bigint(20) NOT NULL, `claim_no` varchar(32) NULL DEFAULT NULL, `policy_id` bigint(20) NULL DEFAULT NULL, `policy_no` varchar(32) NULL DEFAULT NULL, `cust_name` varchar(50) NULL DEFAULT NULL, `product_type` varchar(20) NULL DEFAULT NULL, `report_date` date NULL DEFAULT NULL, `claim_type` varchar(20) NULL DEFAULT NULL, `claim_amount` decimal(12, 2) NULL DEFAULT NULL, `settle_amount` decimal(12, 2) NULL DEFAULT NULL, `status` varchar(12) NULL DEFAULT NULL, `province` varchar(20) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ins_customer` ( `id` bigint(20) NOT NULL, `cust_no` varchar(32) NULL DEFAULT NULL, `cust_name` varchar(50) NULL DEFAULT NULL, `gender` varchar(4) NULL DEFAULT NULL, `age` int(11) NULL DEFAULT NULL, `province` varchar(20) NULL DEFAULT NULL, `city` varchar(20) NULL DEFAULT NULL, `region` varchar(10) NULL DEFAULT NULL, `occupation` varchar(20) NULL DEFAULT NULL, `cust_level` varchar(10) NULL DEFAULT NULL, `reg_date` date NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `ins_policy` ( `id` bigint(20) NOT NULL, `policy_no` varchar(32) NULL DEFAULT NULL, `cust_id` bigint(20) NULL DEFAULT NULL, `cust_name` varchar(50) NULL DEFAULT NULL, `product_name` varchar(50) NULL DEFAULT NULL, `product_type` varchar(20) NULL DEFAULT NULL, `channel` varchar(20) NULL DEFAULT NULL, `premium` decimal(12, 2) NULL DEFAULT NULL, `coverage_amount` decimal(14, 2) NULL DEFAULT NULL, `term_years` int(11) NULL DEFAULT NULL, `sign_date` date NULL DEFAULT NULL, `effect_date` date NULL DEFAULT NULL, `expire_date` date NULL DEFAULT NULL, `status` varchar(12) NULL DEFAULT NULL, `province` varchar(20) NULL DEFAULT NULL, `region` varchar(10) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `jimu_dict` ( `id` varchar(32) NOT NULL, `dict_name` varchar(100) NULL DEFAULT NULL, `dict_code` varchar(100) NULL DEFAULT NULL, `description` varchar(255) NULL DEFAULT NULL, `del_flag` int(1) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `type` int(1) UNSIGNED ZEROFILL NULL DEFAULT 0, `tenant_id` varchar(10) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uk_sd_dict_code`(`dict_code`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_dict_item` ( `id` varchar(32) NOT NULL, `dict_id` varchar(32) NULL DEFAULT NULL, `item_text` varchar(100) NULL DEFAULT NULL, `item_value` varchar(100) NULL DEFAULT NULL, `description` varchar(255) NULL DEFAULT NULL, `sort_order` int(10) NULL DEFAULT NULL, `status` int(11) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_sdi_role_dict_id`(`dict_id`) USING BTREE, INDEX `idx_sdi_role_sort_order`(`sort_order`) USING BTREE, INDEX `idx_sdi_status`(`status`) USING BTREE, INDEX `idx_sdi_dict_val`(`dict_id`, `item_value`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report` ( `id` varchar(32) NOT NULL, `code` varchar(50) NULL DEFAULT NULL, `name` varchar(50) NULL DEFAULT NULL, `note` varchar(255) NULL DEFAULT NULL, `status` varchar(10) NULL DEFAULT NULL, `type` varchar(50) NULL DEFAULT NULL, `json_str` longtext NULL, `api_url` varchar(255) NULL DEFAULT NULL, `thumb` text NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `del_flag` tinyint(1) NULL DEFAULT NULL, `api_method` varchar(255) NULL DEFAULT NULL, `api_code` varchar(255) NULL DEFAULT NULL, `template` tinyint(1) NULL DEFAULT NULL, `view_count` bigint(15) NULL DEFAULT 0, `css_str` text NULL, `js_str` text NULL, `py_str` text NULL, `tenant_id` varchar(10) NULL DEFAULT NULL, `update_count` int(11) NULL DEFAULT 0, `submit_form` tinyint(1) NULL DEFAULT NULL, `is_multi_sheet` tinyint(4) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uniq_jmreport_code`(`code`) USING BTREE, INDEX `uniq_jmreport_createby`(`create_by`) USING BTREE, INDEX `uniq_jmreport_delflag`(`del_flag`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_category` ( `id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `parent_id` varchar(32) NULL DEFAULT NULL, `iz_leaf` int(1) NULL DEFAULT NULL, `source_type` varchar(10) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` timestamp NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` timestamp NULL DEFAULT NULL, `tenant_id` varchar(11) NULL DEFAULT NULL, `del_flag` int(1) NULL DEFAULT NULL, `sort_no` int(11) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_data_source` ( `id` varchar(36) NOT NULL, `name` varchar(100) NULL DEFAULT NULL, `report_id` varchar(100) NULL DEFAULT NULL, `code` varchar(100) NULL DEFAULT NULL, `remark` varchar(200) NULL DEFAULT NULL, `db_type` varchar(10) NULL DEFAULT NULL, `db_driver` varchar(100) NULL DEFAULT NULL, `db_url` varchar(500) NULL DEFAULT NULL, `db_username` varchar(100) NULL DEFAULT NULL, `db_password` varchar(100) NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `connect_times` int(11) NULL DEFAULT 0, `tenant_id` varchar(10) NULL DEFAULT NULL, `type` varchar(10) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_db` ( `id` varchar(36) NOT NULL, `jimu_report_id` varchar(32) NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `db_code` varchar(32) NULL DEFAULT NULL, `db_ch_name` varchar(50) NULL DEFAULT NULL, `db_type` varchar(32) NULL DEFAULT NULL, `db_table_name` varchar(32) NULL DEFAULT NULL, `db_dyn_sql` longtext NULL, `db_key` varchar(32) NULL DEFAULT NULL, `tb_db_key` varchar(32) NULL DEFAULT NULL, `tb_db_table_name` varchar(32) NULL DEFAULT NULL, `java_type` varchar(32) NULL DEFAULT NULL, `java_value` varchar(255) NULL DEFAULT NULL, `api_url` varchar(255) NULL DEFAULT NULL, `api_method` varchar(255) NULL DEFAULT NULL, `is_list` varchar(10) NULL DEFAULT '0', `is_page` varchar(10) NULL DEFAULT NULL, `db_source` varchar(255) NULL DEFAULT NULL, `db_source_type` varchar(50) NULL DEFAULT NULL, `json_data` text NULL, `api_convert` varchar(255) NULL DEFAULT NULL, `iz_shared_source` int(1) NULL DEFAULT NULL, `jimu_shared_source_id` varchar(32) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_jmreportdb_db_key`(`db_key`) USING BTREE, INDEX `idx_jimu_report_id`(`jimu_report_id`) USING BTREE, INDEX `idx_db_source_id`(`db_source`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_db_field` ( `id` varchar(36) NOT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `jimu_report_db_id` varchar(32) NULL DEFAULT NULL, `field_name` varchar(80) NULL DEFAULT NULL, `field_name_physics` varchar(200) NULL DEFAULT NULL, `field_text` varchar(50) NULL DEFAULT NULL, `widget_type` varchar(50) NULL DEFAULT NULL, `widget_width` int(10) NULL DEFAULT NULL, `order_num` int(3) NULL DEFAULT NULL, `search_flag` int(3) NULL DEFAULT 0, `search_mode` int(3) NULL DEFAULT NULL, `dict_code` varchar(255) NULL DEFAULT NULL, `search_value` varchar(100) NULL DEFAULT NULL, `search_format` varchar(50) NULL DEFAULT NULL, `ext_json` text NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_jrdf_jimu_report_db_id`(`jimu_report_db_id`) USING BTREE, INDEX `idx_dbfield_order_num`(`order_num`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_db_param` ( `id` varchar(36) NOT NULL, `jimu_report_head_id` varchar(36) NOT NULL, `param_name` varchar(32) NOT NULL, `param_txt` varchar(32) NULL DEFAULT NULL, `param_value` varchar(1000) NULL DEFAULT NULL, `order_num` int(11) NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `search_flag` int(1) NULL DEFAULT NULL, `widget_type` varchar(50) NULL DEFAULT NULL, `search_mode` int(1) NULL DEFAULT NULL, `dict_code` varchar(255) NULL DEFAULT NULL, `search_format` varchar(50) NULL DEFAULT NULL, `ext_json` text NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_jrdp_jimu_report_head_id`(`jimu_report_head_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_export_job` ( `id` varchar(32) NOT NULL, `name` varchar(100) NULL DEFAULT NULL, `begin_time` datetime NULL DEFAULT NULL, `end_time` datetime NULL DEFAULT NULL, `exec_interval` varchar(100) NULL DEFAULT NULL, `report_conf` text NULL, `last_run_time` datetime NULL DEFAULT NULL, `receiver_email` text NULL, `file_sync_path` varchar(255) NULL DEFAULT NULL, `status` int(11) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_export_log` ( `id` varchar(32) NOT NULL, `batch_no` varchar(50) NULL DEFAULT NULL, `export_channel` varchar(20) NULL DEFAULT NULL, `export_from` varchar(20) NULL DEFAULT NULL, `from_id` varchar(32) NULL DEFAULT NULL, `export_type` varchar(10) NULL DEFAULT NULL, `report_id` text NULL, `download_path` varchar(255) NULL DEFAULT NULL, `status` varchar(15) NULL DEFAULT NULL, `err_msg` text NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` varchar(10) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `jimu_report_ext_data` ( `id` varchar(32) NOT NULL, `biz_type` varchar(100) NOT NULL, `name` varchar(200) NULL DEFAULT NULL, `descr` varchar(500) NULL DEFAULT NULL, `tags` varchar(255) NULL DEFAULT NULL, `data_value` longtext NULL, `metadata` varchar(500) NULL DEFAULT NULL, `status` tinyint(4) NULL DEFAULT 1, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_biz`(`biz_type`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `jimu_report_icon_lib` ( `id` varchar(32) NOT NULL, `name` varchar(100) NULL DEFAULT NULL, `type` varchar(32) NULL DEFAULT NULL, `image_url` varchar(255) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_link` ( `id` varchar(32) NOT NULL, `report_id` varchar(32) NULL DEFAULT NULL, `parameter` text NULL, `eject_type` varchar(1) NULL DEFAULT NULL, `link_name` varchar(255) NULL DEFAULT NULL, `api_method` varchar(1) NULL DEFAULT NULL, `link_type` varchar(1) NULL DEFAULT NULL, `api_url` varchar(1000) NULL DEFAULT NULL, `link_chart_id` varchar(50) NULL DEFAULT NULL, `expression` varchar(255) NULL DEFAULT NULL, `requirement` varchar(255) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `uniq_link_reportid`(`report_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_map` ( `id` varchar(64) NOT NULL, `label` varchar(125) NULL DEFAULT NULL, `name` varchar(125) NULL DEFAULT NULL, `data` longtext NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `del_flag` varchar(1) NULL DEFAULT NULL, `sys_org_code` varchar(64) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uniq_jmreport_map_name`(`name`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_map_copy1` ( `id` varchar(64) NOT NULL, `label` varchar(125) NULL DEFAULT NULL, `name` varchar(125) NULL DEFAULT NULL, `data` longtext NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `del_flag` varchar(1) NULL DEFAULT NULL, `sys_org_code` varchar(64) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uniq_jmreport_map_name`(`name`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_share` ( `id` varchar(32) NOT NULL, `report_id` varchar(32) NULL DEFAULT NULL, `preview_url` varchar(1000) NULL DEFAULT NULL, `preview_lock` varchar(4) NULL DEFAULT NULL, `last_update_time` datetime NULL DEFAULT NULL, `term_of_validity` varchar(1) NULL DEFAULT NULL, `status` varchar(1) NULL DEFAULT NULL, `preview_lock_status` varchar(1) NULL DEFAULT NULL, `share_token` varchar(50) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uniq_report_id`(`report_id`) USING BTREE, INDEX `idx_jrs_share_token`(`share_token`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `jimu_report_sheet` ( `id` varchar(64) NOT NULL, `report_id` varchar(64) NOT NULL, `sheet_name` varchar(255) NOT NULL, `sheet_order` int(11) NOT NULL, `json_str` longtext NULL, `create_time` datetime NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `create_by` varchar(64) NULL DEFAULT NULL, `update_by` varchar(64) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_report_id`(`report_id`) USING BTREE, INDEX `idx_sheet_order`(`report_id`, `sheet_order`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `onl_drag_comp` ( `id` varchar(32) NOT NULL, `parent_id` varchar(32) NULL DEFAULT NULL, `comp_name` varchar(50) NULL DEFAULT NULL, `comp_type` varchar(20) NULL DEFAULT NULL, `icon` varchar(50) NULL DEFAULT NULL, `order_num` int(11) NULL DEFAULT NULL, `type_id` int(11) NULL DEFAULT NULL, `comp_config` longtext NULL, `status` varchar(2) NULL DEFAULT '0', `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `onl_drag_dataset_head` ( `id` varchar(32) NOT NULL, `name` varchar(100) NOT NULL, `code` varchar(36) NULL DEFAULT NULL, `parent_id` varchar(36) NULL DEFAULT NULL, `db_source` varchar(100) NULL DEFAULT NULL, `query_sql` varchar(5000) NULL DEFAULT '0', `content` varchar(1000) NULL DEFAULT NULL, `iz_agent` varchar(10) NULL DEFAULT '0', `data_type` varchar(50) NULL DEFAULT NULL, `api_method` varchar(10) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `low_app_id` varchar(32) NULL DEFAULT NULL, `tenant_id` int(10) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `onl_drag_dataset_item` ( `id` varchar(32) NOT NULL, `head_id` varchar(36) NOT NULL, `field_name` varchar(36) NULL DEFAULT NULL, `field_txt` varchar(1000) NULL DEFAULT NULL, `field_type` varchar(10) NULL DEFAULT NULL, `widget_type` varchar(30) NULL DEFAULT NULL, `dict_code` varchar(500) NULL DEFAULT NULL, `dict_table` varchar(125) NULL DEFAULT NULL, `dict_text` varchar(125) NULL DEFAULT NULL, `iz_show` varchar(5) NULL DEFAULT NULL, `iz_search` varchar(10) NULL DEFAULT NULL, `iz_total` varchar(5) NULL DEFAULT NULL, `search_mode` varchar(10) NULL DEFAULT NULL, `order_num` int(11) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_oddi_head_id`(`head_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `onl_drag_dataset_param` ( `id` varchar(36) NOT NULL, `head_id` varchar(36) NOT NULL, `param_name` varchar(32) NOT NULL, `param_txt` varchar(32) NULL DEFAULT NULL, `param_value` varchar(1000) NULL DEFAULT NULL, `order_num` int(11) NULL DEFAULT NULL, `iz_search` int(11) NULL DEFAULT NULL, `widget_type` varchar(50) NULL DEFAULT NULL, `search_mode` int(11) NULL DEFAULT NULL, `dict_code` varchar(255) NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_oddp_head_id`(`head_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `onl_drag_page` ( `id` varchar(50) NOT NULL, `name` varchar(100) NULL DEFAULT NULL, `path` varchar(100) NULL DEFAULT NULL, `background_color` varchar(10) NULL DEFAULT NULL, `background_image` varchar(255) NULL DEFAULT NULL, `design_type` int(1) NULL DEFAULT NULL, `theme` varchar(10) NULL DEFAULT NULL, `style` varchar(20) NULL DEFAULT NULL, `cover_url` varchar(500) NULL DEFAULT NULL, `des_json` varchar(1000) NULL DEFAULT NULL, `template` longtext NULL, `protection_code` varchar(32) NULL DEFAULT NULL, `type` varchar(64) NULL DEFAULT NULL, `iz_template` varchar(10) NULL DEFAULT '0', `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `low_app_id` varchar(50) NULL DEFAULT NULL, `tenant_id` int(10) NULL DEFAULT NULL, `update_count` int(10) NULL DEFAULT 1, `visits_num` int(11) NULL DEFAULT NULL, `del_flag` int(11) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `onl_drag_page_comp` ( `id` varchar(32) NOT NULL, `parent_id` varchar(32) NULL DEFAULT NULL, `page_Id` varchar(50) NULL DEFAULT NULL, `comp_id` varchar(32) NULL DEFAULT NULL, `component` varchar(50) NULL DEFAULT NULL, `config` longtext NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `onl_drag_share` ( `id` varchar(32) NOT NULL, `drag_id` varchar(32) NULL DEFAULT NULL, `preview_url` varchar(1000) NULL DEFAULT NULL, `preview_lock` varchar(4) NULL DEFAULT NULL, `last_update_time` datetime NULL DEFAULT NULL, `term_of_validity` varchar(1) NULL DEFAULT NULL, `status` varchar(1) NULL DEFAULT NULL, `preview_lock_status` varchar(1) NULL DEFAULT NULL, `share_token` varchar(32) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, UNIQUE INDEX `uniq_ods_drag_id`(`drag_id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `onl_drag_table_relation` ( `id` varchar(50) NOT NULL, `aggregation_name` varchar(100) NULL DEFAULT NULL, `aggregation_desc` varchar(100) NULL DEFAULT NULL, `relation_forms` longtext NULL, `filter_condition` longtext NULL, `header_fields` longtext NULL, `calculate_fields` longtext NULL, `validate_info` longtext NULL, `del_flag` tinyint(1) NULL DEFAULT NULL, `low_app_id` varchar(50) NULL DEFAULT NULL, `tenant_id` int(11) NULL DEFAULT NULL, `create_by` varchar(50) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_aggregation_name`(`aggregation_name`) USING BTREE, INDEX `idx_del_flag`(`del_flag`) USING BTREE, INDEX `idx_tenant_id`(`tenant_id`) USING BTREE, INDEX `idx_create_by`(`create_by`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `rep_demo_dxtj` ( `id` varchar(36) NOT NULL, `name` varchar(50) NULL DEFAULT NULL, `gtime` datetime NULL DEFAULT NULL, `update_by` varchar(50) NULL DEFAULT NULL, `jphone` varchar(125) NULL DEFAULT NULL, `birth` datetime NULL DEFAULT NULL, `hukou` varchar(32) NULL DEFAULT NULL, `laddress` varchar(125) NULL DEFAULT NULL, `jperson` varchar(32) NULL DEFAULT NULL, `sex` varchar(32) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `rep_demo_employee` ( `id` varchar(10) NOT NULL, `num` varchar(50) NULL DEFAULT NULL, `name` varchar(100) NULL DEFAULT NULL, `sex` varchar(10) NULL DEFAULT NULL, `birthday` datetime NULL DEFAULT NULL, `nation` varchar(30) NULL DEFAULT NULL, `political` varchar(30) NULL DEFAULT NULL, `native_place` varchar(30) NULL DEFAULT NULL, `height` varchar(30) NULL DEFAULT NULL, `weight` varchar(30) NULL DEFAULT NULL, `health` varchar(30) NULL DEFAULT NULL, `id_card` varchar(80) NULL DEFAULT NULL, `education` varchar(30) NULL DEFAULT NULL, `school` varchar(80) NULL DEFAULT NULL, `major` varchar(80) NULL DEFAULT NULL, `address` varchar(100) NULL DEFAULT NULL, `zip_code` varchar(30) NULL DEFAULT NULL, `email` varchar(30) NULL DEFAULT NULL, `phone` varchar(30) NULL DEFAULT NULL, `foreign_language` varchar(30) NULL DEFAULT NULL, `foreign_language_level` varchar(30) NULL DEFAULT NULL, `computer_level` varchar(30) NULL DEFAULT NULL, `graduation_time` datetime NULL DEFAULT NULL, `arrival_time` datetime NULL DEFAULT NULL, `positional_titles` varchar(30) NULL DEFAULT NULL, `education_experience` text NULL, `work_experience` text NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `del_flag` tinyint(1) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `rep_demo_gongsi` ( `id` int(11) NOT NULL AUTO_INCREMENT, `gname` varchar(125) NOT NULL, `gdata` varchar(255) NOT NULL, `tdata` varchar(125) NOT NULL, `didian` varchar(255) NOT NULL, `zhaiyao` varchar(255) NOT NULL, `num` varchar(255) NOT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `rep_demo_jianpiao` ( `id` int(11) NOT NULL AUTO_INCREMENT, `bnum` varchar(125) NOT NULL, `ftime` varchar(125) NOT NULL, `sfkong` varchar(125) NOT NULL, `kaishi` varchar(125) NOT NULL, `jieshu` varchar(125) NOT NULL, `hezairen` varchar(125) NOT NULL, `jpnum` varchar(125) NOT NULL, `shihelv` varchar(125) NOT NULL, `s_id` int(11) NOT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 87 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `rep_demo_xiaoshou` ( `id` int(11) NOT NULL AUTO_INCREMENT, `hnum` varchar(125) NOT NULL, `hname` varchar(125) NOT NULL, `xinghao` varchar(125) NOT NULL, `fahuocangku` varchar(125) NOT NULL, `danwei` varchar(125) NOT NULL, `num` int(11) NOT NULL, `danjia` varchar(125) NOT NULL, `zhekoulv` int(11) NOT NULL, `xiaoshoujine` varchar(125) NOT NULL, `beizhu` varchar(125) NULL DEFAULT NULL, `s_id` varchar(11) NOT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 19 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `sys_log` ( `id` varchar(32) NOT NULL, `log_type` int(3) NULL DEFAULT NULL, `log_content` longtext NULL, `operate_type` int(2) NULL DEFAULT NULL, `userid` varchar(32) NULL DEFAULT NULL, `username` varchar(100) NULL DEFAULT NULL, `ip` varchar(100) NULL DEFAULT NULL, `method` varchar(1000) NULL DEFAULT NULL, `request_url` varchar(255) NULL DEFAULT NULL, `request_param` longtext NULL, `request_type` varchar(10) NULL DEFAULT NULL, `cost_time` bigint(20) NULL DEFAULT NULL, `create_by` varchar(32) NULL DEFAULT NULL, `create_time` datetime NULL DEFAULT NULL, `update_by` varchar(32) NULL DEFAULT NULL, `update_time` datetime NULL DEFAULT NULL, `tenant_id` int(10) NULL DEFAULT NULL, `client_type` varchar(5) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE, INDEX `idx_sl_userid`(`userid`) USING BTREE, INDEX `idx_sl_log_type`(`log_type`) USING BTREE, INDEX `idx_sl_operate_type`(`operate_type`) USING BTREE, INDEX `idx_sl_create_time`(`create_time`) USING BTREE ) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `test_customer` ( `id` int(32) NOT NULL AUTO_INCREMENT, `code` varchar(50) NULL DEFAULT NULL, `name` varchar(50) NULL DEFAULT NULL, `address` varchar(100) NULL DEFAULT NULL, `yylx` varchar(2) NULL DEFAULT NULL, `zyyw` varchar(255) NULL DEFAULT NULL, `clsj` date NULL DEFAULT NULL, `fzr` varchar(50) NULL DEFAULT NULL, `phone` varchar(11) NULL DEFAULT NULL, `khyj` varchar(255) NULL DEFAULT NULL, `xypd` varchar(255) NULL DEFAULT NULL, `tbr` varchar(50) NULL DEFAULT NULL, `depts` varchar(50) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `test_monthly_report` ( `id` varchar(50) NOT NULL, `by_sjfdl_yg` double(11, 2) NULL DEFAULT NULL, `lj_sjfdl_yg` double(11, 2) NULL DEFAULT NULL, `by_sjfdl_wg` double(11, 2) NULL DEFAULT NULL, `lj_sjfdl_wg` double(11, 2) NULL DEFAULT NULL, `by_khfdl` double(11, 2) NULL DEFAULT NULL, `lj_khfdl` double(11, 2) NULL DEFAULT NULL, `by_zdrfd` double(11, 2) NULL DEFAULT NULL, `lj_zdrfd` double(11, 2) NULL DEFAULT NULL, `by_ypjzdcl` double(11, 2) NULL DEFAULT NULL, `lj_ypjzdcl` double(11, 2) NULL DEFAULT NULL, `by_ypjzxcl` double(11, 2) NULL DEFAULT NULL, `lj_ypjzxcl` double(11, 2) NULL DEFAULT NULL, `by_qmzjrl` double(11, 2) NULL DEFAULT NULL, `lj_qmzjrl` double(11, 2) NULL DEFAULT NULL, `by_fdddjh` double(11, 2) NULL DEFAULT NULL, `lj_fdddjh` double(11, 2) NULL DEFAULT NULL, `by_jkzsl` double(11, 2) NULL DEFAULT NULL, `lj_jkzsl` double(11, 2) NULL DEFAULT NULL, `by_jyl` double(11, 2) NULL DEFAULT NULL, `lj_jyl` double(11, 2) NULL DEFAULT NULL, `by_zdjyl_zhi` double(11, 2) NULL DEFAULT NULL, `lj_zdjyl_zhi` double(11, 2) NULL DEFAULT NULL, `by_zdjyl_sj` double(11, 2) NULL DEFAULT NULL, `lj_zdjyl_sj` double(11, 2) NULL DEFAULT NULL, `by_zdrkll_zhi` double(11, 2) NULL DEFAULT NULL, `lj_zdrkll_zhi` double(11, 2) NULL DEFAULT NULL, `by_zdrkll_sj` double(11, 2) NULL DEFAULT NULL, `lj_zdrkll_sj` double(11, 2) NULL DEFAULT NULL, `by_zxrkll_zhi` double(11, 2) NULL DEFAULT NULL, `lj_zxrkll_zhi` double(11, 2) NULL DEFAULT NULL, `by_zxrkll_sj` double(11, 2) NULL DEFAULT NULL, `lj_zxrkll_sj` double(11, 2) NULL DEFAULT NULL, `by_jyts` double(11, 2) NULL DEFAULT NULL, `lj_jyts` double(11, 2) NULL DEFAULT NULL, `by_qsts` double(11, 2) NULL DEFAULT NULL, `lj_qsts` double(11, 2) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `test_order` ( `id` varchar(32) NOT NULL, `order_name` varchar(50) NULL DEFAULT NULL, `order_no` varchar(50) NULL DEFAULT NULL, `order_sign_date` datetime NULL DEFAULT NULL, `order_delivery_date` datetime NULL DEFAULT NULL, `order_coms` varchar(50) NULL DEFAULT NULL, `order_pers` varchar(50) NULL DEFAULT NULL, `order_phone` varchar(15) NULL DEFAULT NULL, `fzr` varchar(50) NULL DEFAULT NULL, `depts` varchar(50) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `test_order_pros` ( `id` varchar(32) NOT NULL, `pro_name` varchar(50) NULL DEFAULT NULL, `pro_no` varchar(50) NULL DEFAULT NULL, `pro_count` varchar(11) NULL DEFAULT NULL, `pro_price` decimal(10, 2) NULL DEFAULT NULL, `pro_unit` varchar(10) NULL DEFAULT NULL, `pro_model` varchar(10) NULL DEFAULT NULL, `main_id` varchar(32) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `test_resume` ( `id` int(32) NOT NULL AUTO_INCREMENT, `name` varchar(50) NULL DEFAULT NULL, `sex` varchar(2) NULL DEFAULT NULL, `birthday` date NULL DEFAULT NULL, `phone` varchar(11) NULL DEFAULT NULL, `email` varchar(50) NULL DEFAULT NULL, `address` varchar(255) NULL DEFAULT NULL, `native_place` varchar(200) NULL DEFAULT NULL, `nation` varchar(100) NULL DEFAULT NULL, `political_outlook` varchar(50) NULL DEFAULT NULL, `education` varchar(10) NULL DEFAULT NULL, `graduation_school` varchar(50) NULL DEFAULT NULL, `self_evaluation` varchar(255) NULL DEFAULT NULL, `salary_expectation` decimal(10, 2) NULL DEFAULT NULL, `edu_experience` varchar(255) NULL DEFAULT NULL, `work_experience` varchar(255) NULL DEFAULT NULL, PRIMARY KEY (`id`) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `tmp_report_data_1` ( `monty` varchar(255) NULL DEFAULT NULL, `main_income` decimal(10, 2) NULL DEFAULT NULL, `total` decimal(10, 2) NULL DEFAULT NULL, `his_lowest` decimal(10, 2) NULL DEFAULT NULL, `his_average` decimal(10, 2) NULL DEFAULT NULL, `his_highest` decimal(10, 2) NULL DEFAULT NULL ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `tmp_report_data_income` ( `biz_income` varchar(100) NULL DEFAULT NULL, `bx_jj_yongjin` decimal(10, 2) NULL DEFAULT NULL, `bx_zx_money` decimal(10, 2) NULL DEFAULT NULL, `chengbao_gz_money` decimal(10, 2) NULL DEFAULT NULL, `bx_gg_moeny` decimal(10, 2) NULL DEFAULT NULL, `tb_zx_money` decimal(10, 2) NULL DEFAULT NULL, `neikong_zx_money` decimal(10, 2) NULL DEFAULT NULL, `total` decimal(10, 2) NULL DEFAULT NULL ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS=1;
